# Generated by Django 3.0.3 on 2020-02-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_date', models.DateTimeField(verbose_name='date published')),
                ('etat_couvain', models.CharField(max_length=20)),
                ('nb_cadrecouvain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric_hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
