# Generated by Django 3.0.3 on 2020-02-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200222_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric_hive',
            name='acq_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
