# Generated by Django 3.0.3 on 2020-02-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200222_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric_Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rucher', models.IntegerField(default=0)),
                ('acq_date', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(default=0)),
                ('humidite', models.FloatField(default=0)),
                ('pression', models.FloatField(default=0)),
                ('pluie', models.FloatField(default=0)),
            ],
        ),
    ]
