# Generated by Django 3.0.3 on 2020-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_metric_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_hive',
            name='traitement',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='metric_hive',
            name='humidite',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='metric_hive',
            name='sound',
            field=models.FloatField(default=0),
        ),
    ]
