# Generated by Django 3.0.3 on 2020-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200228_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric_env',
            name='luminosite',
            field=models.FloatField(default=0),
        ),
    ]
