# Generated by Django 3.0.3 on 2020-02-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_metric_env_luminosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric_hive',
            name='hive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Check_Hive'),
        ),
    ]
