# Generated by Django 3.0.3 on 2020-06-11 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0014_auto_20200422_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_firstname', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=20)),
                ('u_mail', models.CharField(max_length=30, unique=True)),
                ('u_telephone', models.CharField(max_length=15)),
                ('u_etsname', models.CharField(max_length=20)),
                ('u_etsadresse', models.CharField(max_length=50)),
                ('u_etstown', models.CharField(max_length=30)),
                ('u_estcountry', models.CharField(max_length=20)),
                ('u_esttelephone', models.CharField(max_length=15)),
                ('u_fkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='apiaries',
            name='a_fkuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
