# Generated by Django 3.0.3 on 2020-06-17 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200611_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='h_queencolor',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='h_queendate',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='h_queentype',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='h_swarmdate',
        ),
        migrations.AddField(
            model_name='hive',
            name='h_boxdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
